spring:
     application:
          name: webhooks-springboot
     datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/school-db
          username: user
          password: pass
     jpa:
          hibernate:
               ddl-auto: update
          show-sql: true
