services:
     mysql:
          image: 'mysql:latest'
          environment:
               - MYSQL_DATABASE=school-db
               - MYSQL_PASSWORD=pass
               - MYSQL_ROOT_PASSWORD=root
               - MYSQL_USER=user
          ports:
               - 3306:3306
